### ISSUE TITLE
You can only call nargin/nargout from within a MATLAB implementation

### ISSUE THREAD

**Issue by praveenlovely** [johannesu/stereo#1]
Hi,

I was trying to reproduce your code for generating a disparity map from the stereo input images
However, I got the following error in MATLAB.

```
Error using nargin
You can only call nargin/nargout from within a MATLAB function.

Error in vgg_mexcompile_script (line 20)
if nargin == 2 && isequal(varargin{1}, 'compile')

Error in vgg_segment_ms (line 36)
vgg_mexcompile_script; % Compilation happens in this script

Error in dispmap_globalstereo/preprocess (line 391)
			info.segment = vgg_segment_ms(Rorig, self.options.seg_params(1), ...

Error in dispmap_globalstereo (line 55)
			preprocess(self);

Error in example_global (line 29)
dm  = dispmap_globalstereo(images,P, disp_range, disparity_factor, options);
```

Please advise on how to overcome this error

**Comment by johannesu** [comment]
What version of MATLAB are you using?

It looks like MATLAB changed how it handles  [vgg_mexcompile_script.m](https://github.com/johannesu/stereo/blob/master/imrender/vgg/vgg_mexcompile.m) after  MATLAB 2013a (the last version I used), which breaks the included code from http://www.robots.ox.ac.uk/~ojw/software.htm.

Reading the release notes I would guess this could have happened with the release of MATLAB 2016b.

A potential fix would be to make [vgg_mexcompile_script.m](https://github.com/johannesu/stereo/blob/master/imrender/vgg/vgg_mexcompile.m)  a function instead of a script, by adding something like

```
function varargout = vgg_mexcompile_script(varargin)
```

I no longer have access to a MATLAB license, so I cannot test this. If you get it to work, you are very welcome to open up a pull request.

**Comment by johannesu** [comment]
@praveenlovely I was able to test the code on MATLAB 2017a and it worked. What version of MATLAB are you using and what command did you run to get your error?
